### ISSUE TITLE
Attempted to boot, then met with this.

### ISSUE THREAD

**Issue by IncasedDevelopment** [valndev/vaporBooster#5]
```
12.02 05:47:58 [Bot] steam-hour-booster@1.0.1 start
12.02 05:47:58 [Bot] node src/hourBooster.js
12.02 05:47:59 [Bot] * Detected 1 account(s) in the config.
12.02 05:47:59 [Bot] * Starting idling 1 account(s).
12.02 05:47:59 [Bot] * Press CTRL + C to exit.
12.02 05:48:00 [Bot] [jm0ub9db7pl5] Logged into Steam as 76561199362390640
12.02 05:48:00 [Bot] /src/accountHandler.js:120
12.02 05:48:00 [Bot] process.stdout.cursorTo(0);
12.02 05:48:00 [Bot] ^
12.02 05:48:00 [Bot] TypeError: process.stdout.cursorTo is not a function
12.02 05:48:00 [Bot] at EventEmitter.<anonymous> (/src/accountHandler.js:120:19)
12.02 05:48:00 [Bot] at /node_modules/easytimer.js/dist/easytimer.js:171:25
12.02 05:48:00 [Bot] at Array.forEach (<anonymous>)
12.02 05:48:00 [Bot] at EventEmitter.emit (/node_modules/easytimer.js/dist/easytimer.js:170:26)
12.02 05:48:00 [Bot] at dispatchEvent (/node_modules/easytimer.js/dist/easytimer.js:597:20)
12.02 05:48:00 [Bot] at dispatchEvents (/node_modules/easytimer.js/dist/easytimer.js:360:9)
12.02 05:48:00 [Bot] at Timeout.updateTimerAndDispatchEvents [as _onTimeout] (/node_modules/easytimer.js/dist/easytimer.js:329:7)
12.02 05:48:00 [Bot] at listOnTimeout (node:internal/timers:559:17)
12.02 05:48:00 [Bot] at processTimers (node:internal/timers:502:7)
12.02 05:48:00 [Bot] * Timer: 00:00:01
```

**Comment by valndev** [comment]
Could you provide more information?

**Comment by valndev** [comment]
Closing this issue as completed after 2 weeks with no response from the OP.
